version: '3'
services:

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: hoge_db
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_HOST=127.0.0.1
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=hoge
    ports:
      - '3306:3306'
    volumes:
      - data_hgoe:/var/lib/mysql
    networks:
      - default

  web:
    image: node:12
    container_name: hgoe_web
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
      - MYSQL_SERVER=mysql
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - default
    depends_on:
      - db

networks:
  default:

volumes:
  data_hgoe:
