version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - data_hoge:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=hoge
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
volumes:
  - data_hoge